### ISSUE TITLE
Injector Saying cannot inject a 32 bit dll into a 64 bit progress

### ISSUE THREAD

**Issue by flocvomYT** [waxnet/NetWare#100]
Steps i did:
Downloaded from GitHub
Downloaded Injector
Added DLL to injector
selected injector to inject into 1v1.lol(steam)
pressed inject
said ERROR cannot inject a 32 bit dll into a 64 bit progress

**Comment by waxnet** [comment]
Might be a problem with your windows version

**Comment by Zordon1337** [comment]
> Might be a problem with your windows version

Funfact, it seems that he attempted to inject it with some injector like Extreme Injector or maybe Xenos kekw
