### ISSUE TITLE
error code 000A

### ISSUE THREAD

**Issue by vampzz1311** [waxnet/NetWare#101]
![image](https://github.com/user-attachments/assets/26a1380d-375e-4d47-8fba-e2aa17558f94)

**Comment by Zordon1337** [comment]
> @waxnet 

Dude just wait, it was 1 am + he will receive notif anyways and stop asking in every possible issue

**Comment by waxnet** [comment]
> > @waxnet
> 
> Dude just wait, it was 1 am + he will receive notif anyways and stop asking in every possible issue

ong

**Comment by waxnet** [comment]
> ![image](https://private-user-images.githubusercontent.com/179418229/361268045-26a1380d-375e-4d47-8fba-e2aa17558f94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NzM4NzYsIm5iZiI6MTcyNDY3MzU3NiwicGF0aCI6Ii8xNzk0MTgyMjkvMzYxMjY4MDQ1LTI2YTEzODBkLTM3NWUtNGQ0Ny04ZmJhLWUyYWExNzU1OGY5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxMTU5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzRhOWFlNTIxYTY1ZmY2N2YzYmZkZGUwYjI5OGM0OWU1NzY0MjI4YjM3YjE1MTY0ZWJjNTdlMWQ1NDFhZGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GAcuwTi-jz6TvcbQpsahFPwKmJBSIgK1LTRqIypPomY)

restarting steam should do the trick

**Comment by waxnet** [comment]
(and btw if you actually read the error message it would tell you the possible solution)

**Comment by vampzz1311** [comment]
i tried that still no

**Comment by waxnet** [comment]
Are you playing 1v1.lol on steam? And do you have steam or 1v1.lol installed in another drive?

**Comment by waxnet** [comment]
try running as admin

**Comment by Zordon1337** [comment]
> try running as admin

I assume he fixed this but is too lazy to respond

**Comment by vampzz1311** [comment]
> > try running as admin
> 
> I assume he fixed this but is too lazy to respond

i had school sorry

**Comment by vampzz1311** [comment]
> Are you playing 1v1.lol on steam? And do you have steam or 1v1.lol installed in another drive?

yes im playing 1v1.lol on steam
