### ISSUE TITLE
Access Denied Issue

### ISSUE THREAD

**Issue by Luka9030** [waxnet/NetWare#11]
![image_2023-12-15_225755776](https://github.com/waxnet/NetWare/assets/74553197/052d7481-2ba0-4764-91a9-0ebc555aaeb5)

**Comment by waxnet** [comment]
I've seen this error happening to multiple users, if you already tried disabling the antivirus and running inject.cmd as admin but you still got the error there is nothing I can do, that's the only possible solution at the moment.

**Comment by lucioushvh** [comment]
> I've seen this error happening to multiple users, if you already tried disabling the antivirus and running inject.cmd as admin but you still got the error there is nothing I can do, that's the only possible solution at the moment.

yeah it was working perfectly fine now its giving me this error aswell.

**Comment by Luka9030** [comment]
I fixed it I just had to turn on compatibility for windows 8 and install on
disk c instead of f

**Comment by waxnet** [comment]
I'll keep this issue open

**Comment by lucioushvh** [comment]
> I fixed it I just had to turn on compatibility for windows 8 and install on disk c instead of f

and how do you do that?

**Comment by sodareverse** [comment]
1. Make sure your game is in fullscreen
2. Run the injector as administrator
3. Redownload your game inside of your C:/ drive
4. Turn off your anti-virus
5. Turn off riot's vanguard anti cheat
6. Go to your control panel and deinstall x86 and x64 redistributables then redownload them

hope this helped

**Comment by waxnet** [comment]
riot vanguard fr blocks the loader?

**Comment by basmannetjeee** [comment]
> riot vanguard fr blocks the loader?

no, It does not.

**Comment by sodareverse** [comment]
Yes, it does, Riot uses advanced IAT module security calling and blocking any process who's suspected as malicious, and game hacks are known to be recognized as trojans. @basmannetjeee is wrong

**Comment by basmannetjeee** [comment]
> Yes, it does, Riot uses advanced IAT module security calling and blocking any process who's suspected as malicious, and game hacks are known to be recognized as trojans. @basmannetjeee is wrong

What? This is just plain wrong. Riot isn't an antivirus, it tries to prevent processes/applications from doing anything with riot or valorant.

**Comment by sodareverse** [comment]
> > Yes, it does, Riot uses advanced IAT module security calling and blocking any process who's suspected as malicious, and game hacks are known to be recognized as trojans. @basmannetjeee is wrong
> 
> What? This is just plain wrong. Riot isn't an antivirus, it tries to prevent processes/applications from doing anything with riot or valorant.
> 
> EDIT: Btw last time I had this issue with access denied it was because the build architechture was wrong. What cpu do you have @Luka9030 (I know it is fixed I just want to be sure of the issue)

Exactly, "it tries to prevent processes/applications from doing anything with riot or valorant", the actual injector is blocked and automatically causes an error or Riot deletes it as Riot is kernel usermode.

**Comment by sodareverse** [comment]
> schizo post but ok,
> 
> I have only one thing to say and that is that you're chatting out of your ass. This is literally just wrong. Stop schizo posting and spreading retarded comments that aren't true

yeah buddy ok, whatever
