### ISSUE TITLE
problem loading the cheat it says check ur connection or the antivirus but none of those work the error code is 00A1

### ISSUE THREAD

**Issue by Playvreaks1** [waxnet/NetWare#115]
when i open the chet then i press one i get an eroor meassage saying check internet or antivirus i have done both and they have not succseeded the eroor code is 00A1
\

**Comment by waxnet** [comment]
Are you using the loader v3?

**Comment by Playvreaks** [comment]
Yes

**Comment by waxnet** [comment]
Send a vid

**Comment by Playvreaks** [comment]
I can’t video too big but I’ll try again tomorrow for the laoder

**Comment by waxnet** [comment]
wait no lil bro ur retarded

**Comment by waxnet** [comment]
error 001A is only on the old loader, you need to download the latest
