### ISSUE TITLE
THE LINK NO WORKY

### ISSUE THREAD

**Issue by Playvreaks1** [waxnet/NetWare#119]
when i wait an hour for the link  on  link virtisse i get an error 04

**Comment by waxnet** [comment]
Dont refresh the page

**Comment by Playvreaks1** [comment]
then it dosnt download

**Comment by Playvreaks1** [comment]
so then it wont download like tf

**Comment by Playvreaks1** [comment]
this is the ERROR 004 : Invalid LinkVertise hash, repeat LinkVertise process.

**Comment by waxnet** [comment]
It literally tells you what to do

**Comment by waxnet** [comment]
You dont need to touch anything once you click get netware, if you did the shit correctly it should just download the zip

**Comment by Playvreaks1** [comment]
WHERE

**Comment by waxnet** [comment]
What where

**Comment by Playvreaks1** [comment]
ITS DOSNT DOWNLOAD AND I AM A RETARD I AM SORRY OKAY?!

**Comment by waxnet** [comment]
Just look at the video on yt

**Comment by Playvreaks1** [comment]
I Did

**Comment by waxnet** [comment]
Brother

**Comment by waxnet** [comment]
You have to be slow in the head

**Comment by Playvreaks1** [comment]
all it dose is click on the link and when i do t says ullshit

**Comment by Playvreaks1** [comment]
here i will try again be back in 2

**Comment by waxnet** [comment]
> this is the ERROR 004 : Invalid LinkVertise hash, repeat LinkVertise process.

This literally tells you what to do, there is not much to understand

**Comment by Playvreaks1** [comment]
> > this is the ERROR 004 : Invalid LinkVertise hash, repeat LinkVertise process.
> 
> This literally tells you what to do, there is not much to understand

i know i relized after i sent that  message lol

**Comment by waxnet** [comment]
💀

**Comment by Playvreaks1** [comment]
i clicked on te link waited 1min and nothing downloaded

**Comment by Playvreaks1** [comment]
i didnt click on refresh nothing

**Comment by Playvreaks1** [comment]
soooo what do i do

**Comment by Playvreaks1** [comment]
> You dont need to touch anything once you click get netware, if you did the shit correctly it should just download the zip

did :0

**Comment by waxnet** [comment]
Send a vid

**Comment by Playvreaks1** [comment]
can i send one on here
.>

**Comment by Playvreaks1** [comment]
well ofc it worked  when i was recording tell anyone who has the same problem to do it until it worked becaouse i have done it 12 plus times ps thanks for telling me to record becaouse now it works

**Comment by waxnet** [comment]
Ye

**Comment by waxnet** [comment]
Alr
