### ISSUE TITLE
Disable AntiVirus Even If It Is Already Disabled

### ISSUE THREAD

**Issue by HaykoAnderson** [waxnet/NetWare#122]
Can't load the cheat, it tell us to disable our anti virus even if it is already disabled

**Comment by waxnet** [comment]
1v1.LOL went back to il2cpp so the cheat wont work for some time.

**Comment by Ryannbru** [comment]
yeah same problem

**Comment by waxnet** [comment]
> yeah same problem

are u slow?

**Comment by DXC1712** [comment]
dyk an estimated time range of when it could possibly be back up

**Comment by waxnet** [comment]
no

**Comment by Ryannbru** [comment]
fix it dude

**Comment by waxnet** [comment]
> fix it dude

fix it urself lil cuh

**Comment by docogh** [comment]
pressing the dev to fix it isn't gonna make it any faster 😭

**Comment by waxnet** [comment]
fixed
