### ISSUE TITLE
Invalid DOS Signature Loader Error

### ISSUE THREAD

**Issue by UnknownSlayerz** [waxnet/NetWare#125]
anyone elses loader freezes when launching? when you get to close the launcher after it freezes at patching anti cheat it just give you an error (one or more errors occured (invalid DOS signature) ).

![image](https://github.com/user-attachments/assets/6f93c3e3-65d1-4656-9d09-5d68952967da)

**Comment by waxnet** [comment]
never saw that before

**Comment by UnknownSlayerz** [comment]
it was working fine yesterday and all of a sudden it stopped today. Plus the bypass where you revert your game version doesn't work anymore it just crashes the game upon launch.

**Comment by waxnet** [comment]
> it was working fine yesterday and all of a sudden it stopped today. Plus the bypass where you revert your game version doesn't work anymore it just crashes the game upon launch.

you probably did something wrong, it works fine for me
