### ISSUE TITLE
silent aim not working

### ISSUE THREAD

**Issue by Porcodio11** [waxnet/NetWare#15]
silent aim worked for a round then stopped

**Comment by waxnet** [comment]
is it happening every time or it just happened once

**Comment by Porcodio11** [comment]
Happens every time, it might be the new rocket mode they added im not sure but that is what i played

**Comment by waxnet** [comment]
it works for me, are you sure you're using the latest version

**Comment by Porcodio11** [comment]
yeah i am, i dont know why it just doesn't work for me
