### ISSUE TITLE
inject

### ISSUE THREAD

**Issue by bubacik69** [waxnet/NetWare#16]
Where can i find the inject.cmd file?

**Comment by waxnet** [comment]
download the zip file in the releases

**Comment by bubacik69** [comment]
i did but it isnt there
![Snímka obrazovky 2024-01-08 201358](https://github.com/waxnet/NetWare/assets/155895375/7d8a693f-6057-4739-bed5-3d27cc563438)

**Comment by Lemniscatez** [comment]
lil bro you downloaded the source use this url: https://github.com/waxnet/NetWare/releases/download/v1.7.1/NetWare.zip

**Comment by bubacik69** [comment]
ohh tysm

**Comment by bubacik69** [comment]
it wont let me download my google says its harmful is it safe?

**Comment by robin259** [comment]
> it wont let me download my google says its harmful is it safe?

Yes it is, i also use it

**Comment by waxnet** [comment]
> it wont let me download my google says its harmful is it safe?

The file is safe, unfortunately almost anything that includes dll injection is flagged by AVs since its also a practice which is sometimes used by malware. If you dont trust the files you can check their source code by opening them with "https://github.com/dnSpy/dnSpy" ,  hope this helps!
