### ISSUE TITLE
Failed to find mono.dll in target process

### ISSUE THREAD

**Issue by NoobToolzz** [waxnet/NetWare#21]
Game has updated and you'll get this error right now (I think this is why)
I feel like this a small move to hint at the "anti-cheat" 💀 (removing mono.dll ig)
```
Unhandled Exception: SharpMonoInjector.InjectorException: Failed to find mono.dll in the target process
   at SharpMonoInjector.Injector..ctor(String processName)
   at SharpMonoInjector.Console.Program.Main(String[] args)
```

**Comment by Reticls** [comment]
getting this same issue, reply if you found a fix

**Comment by Unverifiedjay** [comment]
the game just updated so ofc the hack isnt going to work for now lol
