### ISSUE TITLE
Cheat Not Working

### ISSUE THREAD

**Issue by LongYears9** [waxnet/NetWare#24]
PLEASE HELP 😭😭 @waxnet

**Comment by K4RNXGEx333** [comment]
I think that it just needs to be updated. Which what I'm trying to figure out

**Comment by waxnet** [comment]
The game is now in il2cpp so this update will take a long time.

**Comment by LongYears9** [comment]
waiting for the next update with more features 🔥

**Comment by tinyblaster** [comment]
it wont even open 
for me

**Comment by waxnet** [comment]
the cheat is not back up and running
