### ISSUE TITLE
earlier issue closed without solution

### ISSUE THREAD

**Issue by paladingames** [waxnet/NetWare#27]
it doesnt work
https://private-user-images.githubusercontent.com/145715625/300162484-a4805ab5-83ac-43c6-b0da-3eaaa0a834bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNzQ0NzUsIm5iZiI6MTcwNjM3NDE3NSwicGF0aCI6Ii8xNDU3MTU2MjUvMzAwMTYyNDg0LWE0ODA1YWI1LTgzYWMtNDNjNi1iMGRhLTNlYWFhMGE4MzRiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxNjQ5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2NmZWY0YzE4Y2I4OTZiN2M0NTI5NmE2MWI1NDA4MGU5NDU3NWNkYjZkMDhkZTNiZGU4ZGI4M2NhNjc1Y2FhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PNoPN2JygdR9Rwcgk5NnkE5sF-gzUbqJb_zHe51An3w

**Comment by waxnet** [comment]
there is already info on it on the discord server and there is a dedicated issue already open
