### ISSUE TITLE
Game Crashes After Injection

### ISSUE THREAD

**Issue by ZelRaccy** [waxnet/NetWare#29]
no matter how i inject it the game crashes after a few seconds  i've even tried using the smi gui instead

https://github.com/waxnet/NetWare/assets/56210314/af17d569-443c-49e0-9cb4-8648adb9ffe5

**Comment by Hogride69** [comment]
same pronlem

**Comment by fin-github** [comment]
yup. same thing

**Comment by TharmsyXD** [comment]
it got patched wait for new update

**Comment by waxnet** [comment]
Its the anticheat, rn im pretty sure it still doesnt ban people but idk

**Comment by fin-github** [comment]
it just detects the injection and kills its process

**Comment by fin-github** [comment]
bypasses have been found. dm me @fincodes on discord for it

**Comment by waxnet** [comment]
true

**Comment by Flip4up** [comment]
What bypass can i use?

**Comment by waxnet** [comment]
just go in the discord server and check the announcements channel for the bypass

**Comment by toninhodjjj** [comment]
discord?

**Comment by NoobToolzz** [comment]
Here's the Discord: https://discord.gg/yuXmsMSSFj -> Check #1v1.lol channel in it.

**Comment by waxnet** [comment]
a loader will be created soon
