### ISSUE TITLE
Game still crashes even with updated Netware released 5hrs ago...

### ISSUE THREAD

**Issue by Lazycoder747** [waxnet/NetWare#34]
I try to use it but as soon as I enable something, it just crashes? Do you guys think there is a way to modify the anticheat so that it thinks NetWare is a trusted process? Or do we have to conceal it altogether? I don't think it is possible to make a solution for this quickly, so if you are working on it, please take your time! :)

**Comment by waxnet** [comment]
check discord

**Comment by Lazycoder747** [comment]
Ok, Thanks so much!
