### ISSUE TITLE
Does not load 

### ISSUE THREAD

**Issue by Crispy0033** [waxnet/NetWare#37]
cheat loader does not load up.

**Comment by waxnet** [comment]
ah yes, truly a helpful issue explaining what is wrong the loader

**Comment by Crispy0033** [comment]
when you launch the loader it loads up the program on the bottom of your task bar but just closes down in .1 seconds

**Comment by esealx** [comment]
> when you launch the loader it loads up the program on the bottom of your task bar but just closes down in .1 seconds

same, did you ever fix it?
