### ISSUE TITLE
injecting

### ISSUE THREAD

**Issue by SoaRGHXST** [waxnet/NetWare#40]
Hey i have a issue with it not injecting can you help me fix it

**Comment by waxnet** [comment]
Describe it

**Comment by SoaRGHXST** [comment]
> Describe it

like with the older versions i inject press insert and it shows but with the new one i inject but nothing pops up

**Comment by waxnet** [comment]
Are you using the loader?

**Comment by SoaRGHXST** [comment]
> Are you using the loader?

yes
