### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by D0nPeppe** [waxnet/NetWare#42]
when i try to inject NetWare on 1v1 LoL, the game crash without explain where is the problem, please help me

**Comment by waxnet** [comment]
Are you using the loader?

**Comment by D0nPeppe** [comment]
> Stai usando il caricatore?

yes, i'm using a loader, but after a few second game crush

**Comment by waxnet** [comment]
if you can send a video or an image

**Comment by Gebruiker13131212** [comment]
> if you can send a video or an image

I have the same problem.

**Comment by D0nPeppe** [comment]
> if you can send a video or an image

I can't cause the video it's too big, here's my discord, i can send it there: DonPeppe

**Comment by waxnet** [comment]
Send it on the discord server and ping me
