### ISSUE TITLE
it wont inject 

### ISSUE THREAD

**Issue by SoaRGHXST** [waxnet/NetWare#45]
When i use the loader nothing pops up in game i dont know what i am doing wrong  i dont know if i gotta put it in my game folder

**Comment by waxnet** [comment]
No you just need to execute the loader nothing else

**Comment by esealx** [comment]
how do I execute the loader?

**Comment by esealx** [comment]
> No you just need to execute the loader nothing else

How do I execute it?

**Comment by waxnet** [comment]
Just double click it bro tf u mean

**Comment by NOOTNOOTNG** [comment]
same issue

**Comment by waxnet** [comment]
If you are getting the error code 000 try restarting steam
