### ISSUE TITLE
how can i build the source code

### ISSUE THREAD

**Issue by zer0gra** [waxnet/NetWare#5]
![image](https://github.com/waxnet/NetWare/assets/140010217/77303651-2255-4ce0-82c1-29808972e596)
as you can see i have 118 errors i just wanted to look trough the source to make sure it isnt a virus

**Comment by waxnet** [comment]
To build the source yourself you need to add the game's dlls as reference, if you don't know how to do so try to search on YouTube or Google and you should find a bunch of tutorials, you will also need to build it as release to avoid other errors or performance issues, you can do so from the top bar on Visual Studio.

**Comment by Proofex-1** [comment]
Add me on discord so i can send you the files
discord: Proofex

**Comment by zer0gra** [comment]
> Add me on discord so i can send you the files discord: Proofex

youre not accepting friend requests
