### ISSUE TITLE
UI goes blank when selecing visual or settings

### ISSUE THREAD

**Issue by NOOTNOOTNG** [waxnet/NetWare#57]
yeah I cannot see anything when selecting the visual option image: 
![image](https://github.com/waxnet/NetWare/assets/161619669/d1a1950f-3d8a-4899-8aca-93483550d01f)

**Comment by waxnet** [comment]
Did you load a config before going in visual or movement?

**Comment by NOOTNOOTNG** [comment]
No, I did not.
The movement tab works, only the settings and visual tabs don't work, and then I have to restart it because I couldn't click anything.

**Comment by waxnet** [comment]
Are you using the loader or are you injecting it without the loader?

**Comment by NOOTNOOTNG** [comment]
I'm using the loader.

**Comment by waxnet** [comment]
Alr I've just released a test/dubug build, try using that and send me a screenshot of the error message that should appear on your screen.

**Comment by NOOTNOOTNG** [comment]
> Alr I've just released a test/dubug build, try using that and send me a screenshot of the error message that should appear on your screen.

where is it?
Can' t find the build.

**Comment by waxnet** [comment]
Alr, the issue should now be fixed, give it a try and tell me if it works.

**Comment by NOOTNOOTNG** [comment]
> Alr, the issue should now be fixed, give it a try and tell me if it works.

yup, it works, thanks (ps. I've come across a user named netware a couple mins ago was that you? I had autoplay on and the other too.)

**Comment by waxnet** [comment]
Nah I dont play the game a lot, I only play it if I have to add or fix stuff to NetWare.
