### ISSUE TITLE
1v1.lol now probably checks if AntiCheat was patched

### ISSUE THREAD

**Issue by Zordon1337** [waxnet/NetWare#59]
Hi!, im not sure if it affects NetWareLoader but it probably does since when i patched AntiCheat(by just removing code inside StartDetection Func) yesterday after new update, game stops starting and its stuck at loading 0%, probably because it detects that AC dll signature is invalid or maybe there is other reason?

**Comment by waxnet** [comment]
Try verifing the game files and disabling it again

**Comment by Zordon1337** [comment]
I've tried it also iirc

**Comment by waxnet** [comment]
that used to happen to me too some time ago but it sorted out eventually, so i dont think its any detection stuff

**Comment by Zordon1337** [comment]
> that used to happen to me too some time ago but it sorted out eventually, so i dont think its any detection stuff

yeah maybe thats just me, looking at 1v1.lol devs it is small chance that they did anything other than just adding CodeStage to their game, even this took them like 1 year i believe? lmao

**Comment by waxnet** [comment]
Yeah lol, the game is working normally for me so idk
