### ISSUE TITLE
Tried to complile on my own and trying to make a paste but it gives 233 errors 

### ISSUE THREAD

**Issue by psxjtwr01** [waxnet/NetWare#60]
I am trying to make a paste (not going to publish) but it gives me 233 errors without even changing a single line of code
![image](https://github.com/waxnet/NetWare/assets/100047007/b8758759-d4c8-430d-a62c-aa10989c9406)

**Comment by psxjtwr01** [comment]
Fixxed all issues but i get this err now
![image](https://github.com/waxnet/NetWare/assets/100047007/2f1d8e14-ca6c-40cd-9382-395e323ad20d)

**Comment by psxjtwr01** [comment]
![image](https://github.com/waxnet/NetWare/assets/100047007/325597c8-3171-403c-9456-22c0d0d101f8)
I have this but it still has err

**Comment by waxnet** [comment]
I have no idea what that error is ngl

**Comment by psxjtwr01** [comment]
> I have no idea what that error is ngl

figured it out i accidently went into properties and changed the Main class so it was expecting Mainx which i guess i pressed when scrolling so yea i fixed it
