### ISSUE TITLE
it is detected as of 4.16.24

### ISSUE THREAD

**Issue by psxjtwr01** [waxnet/NetWare#65]
got my first ban today spoofer not working no more. it was good while it lasted hopefully its easy to bypass but i got hwid banned used 3 diff vpns all new accts got banned

**Comment by Lemniscatez** [comment]
i dont think its an hwid ban but ill look into it

**Comment by psxjtwr01** [comment]
> i dont think its an hwid ban but ill look into it

It was a temporary ban even though it said PERMANANT but i logged in again and now its working fine
but cheat isnt patching anticheat correctly they must of fixed that
