### ISSUE TITLE
Error Code: 002

### ISSUE THREAD

**Issue by reedycat426** [waxnet/NetWare#69]
![Screenshot 2024-04-17 184831](https://github.com/waxnet/NetWare/assets/166476425/a63e1075-28f3-461c-a09e-0afde3b74a0a)

**Comment by RockstarAdvancedGameEngine** [comment]
thats happens to everyone tbh

**Comment by z3ro-c0nfig** [comment]
happends to me too i think its patched

**Comment by waxnet** [comment]
NetWare is not updated right now

**Comment by GEkkehackershier** [comment]
same for me
![Schermafbeelding 2024-04-29 025850](https://github.com/waxnet/NetWare/assets/161137403/279a6f57-b40b-47e0-84ce-bfd3fd0ea467)

**Comment by TJGTA2** [comment]
You can find updated NetWare here:
https://discord.com/invite/yXsqkTBjDv
