### ISSUE TITLE
Error: 002

### ISSUE THREAD

**Issue by TheRealYaroic** [waxnet/NetWare#80]
Any fix?

![snn](https://github.com/waxnet/NetWare/assets/70550877/82a78a09-37f7-4595-9855-6e13ef5ed72d)

**Comment by q0zas** [comment]
no they js wont update it cuz they are lazy

**Comment by LongYears9** [comment]
@waxnet please fix it 😭

**Comment by TJGTA2** [comment]
> no they js wont update it cuz they are lazy

Here's updated NetWare server link: 
https://discord.com/invite/yXsqkTBjDv

**Comment by GoostYTQC** [comment]
> > no they js wont update it cuz they are lazy
> 
> Here's updated NetWare server link: https://discord.com/invite/yXsqkTBjDv

nice try

**Comment by LongYears9** [comment]
Heres updated Netware (real) https://discord.gg/UExAmXyzfH

**Comment by kaxyum** [comment]
same 

> Any fix?
> 
> ![snn](https://private-user-images.githubusercontent.com/70550877/329075493-82a78a09-37f7-4595-9855-6e13ef5ed72d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NjgyNDQsIm5iZiI6MTcxOTY2Nzk0NCwicGF0aCI6Ii83MDU1MDg3Ny8zMjkwNzU0OTMtODJhNzhhMDktMzdmNy00NTk1LTk4NTUtNmUxM2VmNWVkNzJkLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDEzMzIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNGFlZjgwYTliMDdmNTU1NjgxZGIzNzAyODI4Zjc5MDQ5MTMwNGM0YTlhNGIxMDlmNjQ2NzJmODhiY2RhZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-gSmXNLTy7M6tECyKBKiaJulbjH2zEKZ021081CV7gI)

same

**Comment by Zordon1337** [comment]
it won't work anymore because 1v1.lol devs switched to il2cpp
