### ISSUE TITLE
Missing Refrences

### ISSUE THREAD

**Issue by GlockClipz** [waxnet/NetWare#9]
# Whole Lotta Errors
Is there any refrences i should be inserting because theres a insane amount of errors in this project
![image](https://github.com/waxnet/NetWare/assets/85517229/dc2016ad-7294-452b-aca7-e750f605bbee)

**Comment by GlockClipz** [comment]
If u could help that would be a appreciated

**Comment by GlockClipz** [comment]
So should i just add all the dll's as a references

**Comment by Lemniscatez** [comment]
Yes

**Comment by waxnet** [comment]
Did you solve the problem?
