### ISSUE TITLE
Possible Future Bypass

### ISSUE THREAD

**Issue by Zordon1337** [waxnet/NetWare#97]
so basically this cheat WILL NOT work anymore because the 1v1.lol developers switched to il2cpp backend from mono

**Comment by Zordon1337** [comment]
found way to bypass, im going to make guide and pull request
![image](https://github.com/user-attachments/assets/bf507bf0-0e4c-4cf9-8ad9-82e712fb1b2d)

**Comment by Zordon1337** [comment]
UPDATE: after looking now, downgrade is not needed, since update released 3 hours ago is using Mono???? wtf
@waxnet

**Comment by waxnet** [comment]
Lol

**Comment by Zordon1337** [comment]
okay so the simplest way would be just downgrading to newest mono depot since they probably don't check the build or if they do just spoof it

**Comment by Zordon1337** [comment]
and since i made my own backend emulator which still allows you to play normally since they use photon to basically every thing mp related: parties and ingame

**Comment by Zordon1337** [comment]
i've joined my friend party from my own backend(my friend was playing on official servers)

**Comment by waxnet** [comment]
pretty cool

**Comment by Zordon1337** [comment]
> pretty cool

backend works with latest version for now, so in case they switch to il2cpp we are ready for that lol

**Comment by vampzz1311** [comment]
how to bypass

**Comment by Zordon1337** [comment]
How to use ability to read?

pon., 26 sie 2024, 02:15 użytkownik vampzz1311 ***@***.***>
napisał:

**Comment by Zordon1337** [comment]
they are back with il2cpp rip
