### ISSUE TITLE
it wont launch

### ISSUE THREAD

**Issue by dfghjkjhgfsd** [waxnet/NetWare#99]
![image](https://github.com/user-attachments/assets/6661a4b9-320e-40b9-87f6-16078a010403)

**Comment by dfghjkjhgfsd** [comment]
please help

**Comment by dfghjkjhgfsd** [comment]
i always get this error

**Comment by dfghjkjhgfsd** [comment]
@waxnet  please help

**Comment by waxnet** [comment]
restart steam
